name: Build
on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.sln'
      - '**.props'
      - '.editorconfig'
    
  pull_request: 
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}

    steps:
      - name: Checkout Code
        id: check-out-code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install dotnet
        id: install-dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Install Java
        id: install-java
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin

      - name: Restore nuget
        id: restore-nuget
        run: dotnet restore ./TBC.slnx

      - name: Lint Code
        id: lint-code
        run: dotnet format ./TBC.slnx --verify-no-changes --no-restore
    
      - name: Run tests with coverage
        id: run-tests
        run: |
          dotnet tool install --global dotnet-sonarscanner
          echo "Installed tools. Setting Path variable."
          export PATH="$PATH:$HOME/.dotnet/tools"
          echo "Path variable updated. Creating coverage directory" 
          
          
          echo "Starting sonnarscanner "
          
          dotnet sonarscanner begin \
            /k:"thebalditect_the-book-club" \
            /o:"thebalditect" \
            /d:sonar.token="$SONAR_TOKEN" \
            /d:sonar.cs.opencover.reportsPaths="src/**/coverage.opencover.xml" \
            /d:sonar.host.url="https://sonarcloud.io"
          
          
          mkdir -p coverage
          dotnet test ./TBC.slnx \
            --configuration Release \
            --no-restore \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover
          
          dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"

